"""add thumbnail_url to levels and level_versions

Revision ID: 8ff7c4e70250
Revises: b7454a8947f0
Create Date: 2026-09-30 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff7c4e70250'
down_revision = 'b7454a8947f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Both nullable, no server_default needed - unlike is_deleted/
    # play_count/completion_count, every pre-existing row correctly has
    # no thumbnail yet (nothing before this migration ever captured
    # one), and NULL already means exactly that.
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('level_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level_versions', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###