"""initial schema

Revision ID: b0c9a57f700e
Revises: 
Create Date: 2026-09-28 18:50:43.986704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0c9a57f700e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_link_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_link_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_link_requests_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_link_requests_requested_at'), ['requested_at'], unique=False)

    op.create_table('twitch_signup_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('twitch_id', sa.String(length=64), nullable=False),
    sa.Column('twitch_display_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=19), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('twitch_id', sa.String(length=64), nullable=True),
    sa.Column('twitch_display_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'DEVELOPER', 'MODERATOR', 'USER', name='user_role'), nullable=False),
    sa.Column('hide_email', sa.Boolean(), nullable=False),
    sa.Column('hide_twitch', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('is_deleted OR email IS NOT NULL OR twitch_id IS NOT NULL', name='users_must_have_an_auth_identity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('twitch_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)

    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=19), nullable=False),
    sa.Column('visibility_state', sa.Enum('DRAFT', 'TESTING', 'PUBLISHED', 'UNPUBLISHED', name='level_visibility_state'), nullable=False),
    sa.Column('latest_published_version_id', sa.Integer(), nullable=True),
    sa.Column('remixed_from_version_id', sa.Integer(), nullable=True),
    sa.Column('remixed_from_level_id', sa.Integer(), nullable=True),
    sa.Column('draft_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('draft_beaten_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['remixed_from_level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('level_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('beaten_at', sa.DateTime(), nullable=True),
    sa.Column('clear_rate_cached', sa.Float(), nullable=True),
    sa.Column('difficulty_label_cached', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'version_number', name='uq_level_versions_level_id_version_number')
    )
    # ### end Alembic commands ###

    # levels.latest_published_version_id and levels.remixed_from_version_id
    # both reference level_versions.id, but level_versions.level_id also
    # references levels.id - a genuine circular FK, which is why these two
    # are modeled with use_alter=True in app/models/level.py. Autogenerate
    # emitted them as inline ForeignKeyConstraint(..., use_alter=True)
    # arguments inside op.create_table('levels', ...) above, but Alembic
    # silently drops any use_alter=True constraint declared that way -
    # verified by diffing this migration's resulting schema against
    # db.create_all()'s: both FKs were simply missing from the DB. Added
    # by hand here as separate op.create_foreign_key() calls instead, run
    # after level_versions exists, which is what actually creates them.
    op.create_foreign_key(
        'fk_levels_latest_published_version_id',
        'levels', 'level_versions',
        ['latest_published_version_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_levels_remixed_from_version_id',
        'levels', 'level_versions',
        ['remixed_from_version_id'], ['id'],
    )


def downgrade():
    # Drop the two hand-added circular FKs first - level_versions can't be
    # dropped while levels still references it.
    op.drop_constraint('fk_levels_remixed_from_version_id', 'levels', type_='foreignkey')
    op.drop_constraint('fk_levels_latest_published_version_id', 'levels', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level_versions')
    op.drop_table('refresh_tokens')
    op.drop_table('login_tokens')
    op.drop_table('levels')
    op.drop_table('email_verification_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_public_id'))

    op.drop_table('users')
    op.drop_table('twitch_signup_tokens')
    with op.batch_alter_table('login_link_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_link_requests_requested_at'))
        batch_op.drop_index(batch_op.f('ix_login_link_requests_identifier'))

    op.drop_table('login_link_requests')
    # ### end Alembic commands ###

    # op.drop_table() drops the tables but, on Postgres, leaves the ENUM
    # types created for the sa.Enum columns above (user_role,
    # level_visibility_state) behind - verified by running upgrade,
    # downgrade, then upgrade again: the second upgrade failed with
    # "type already exists" for user_role. Dropped explicitly here so a
    # downgrade actually returns the database to its pre-migration state.
    sa.Enum(name='level_visibility_state').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=False)