"""add play and completion counts to levels

Revision ID: b7454a8947f0
Revises: 35ad9dfbfceb
Create Date: 2026-09-30 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7454a8947f0'
down_revision = '35ad9dfbfceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Same nullable=False-on-an-existing-table situation as
    # cd6cb256ae04's is_deleted column - server_default='0' backfills
    # every pre-existing row to 0 (accurate: nothing before this
    # migration ever counted a play or completion) in the same ALTER
    # TABLE, then gets dropped once that backfill has applied. Every
    # new row from here on gets 0 from the model's own
    # default=0 (see Level.play_count/completion_count) instead.
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('play_count', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('completion_count', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.alter_column('play_count', server_default=None)
        batch_op.alter_column('completion_count', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('completion_count')
        batch_op.drop_column('play_count')

    # ### end Alembic commands ###