"""add is_deleted to levels

Revision ID: cd6cb256ae04
Revises: b0c9a57f700e
Create Date: 2026-09-29 09:39:39.091900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6cb256ae04'
down_revision = 'b0c9a57f700e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate left this as nullable=False with no default, which
    # fails outright against any table that already has rows (verified:
    # ran this against a levels table seeded with one pre-existing row -
    # "column is_deleted of relation levels contains null values"). Every
    # existing level predates this column and was never deleted, so
    # server_default='false' backfills every existing row to False in
    # the same ALTER TABLE, which is exactly what should have happened
    # to them anyway. Dropped again below once the backfill has applied
    # (see downgrade's mirroring comment) - a version column doesn't
    # need to keep a stale default hanging around at the database level
    # once the app itself is what supplies False for every new row via
    # the model's default=False.
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.alter_column('is_deleted', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###